project_id = "htfhnwhtauvflothadlw"

[functions.generate-nuggets]
verify_jwt = false

[functions.generate-companion]
verify_jwt = false

[functions.nugget-image]
verify_jwt = false

[functions.seed-nuggets]
verify_jwt = false