// Service Worker for PWA functionality
// This file will be auto-generated by next-pwa in production

self.addEventListener('install', (event) => {
  console.log('Service Worker installing.');
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  console.log('Service Worker activating.');
});

self.addEventListener('fetch', (event) => {
  // Handle fetch events here if needed
});